### ISSUE TITLE
The node_modules folder is committed on master.

### ISSUE THREAD

**Issue by WesleyJSO** [JVZELLER/app-client#2]
**steps to reproduce**: download the branch master and execute the npm install command to download the dependencies, you will notice that the process will be completed in no time, then if you run the command quasar dev the console will log some errors (I've already corrected the problem and can't reproduce it anymore to show it here).

**possible solution**: basically delete the node_module folder so that the .gitignore can do its job and exclude from future commits after that, commit the .gitignore with the node_modules folder full path.

Is us.

**Comment by JVZELLER** [comment]
Thanks.

Done in #1

**Comment by JVZELLER** [comment]
Thanks.

Done in #1 Pull Request.
